// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/google/wire"
	"github.com/ljsea6/go-hello-world/app/controllers"
	"github.com/ljsea6/go-hello-world/app/repositories"
	"github.com/ljsea6/go-hello-world/app/services"
)

// Injectors from injector.go:

func Init() *Initialization {
	gormDB := ConnectToDB()
	userRepositoryImpl := repositories.UserRepositoryInit(gormDB)
	userServiceImpl := services.UserServiceInit(userRepositoryImpl)
	userControllerImpl := controllers.UserControllerInit(userServiceImpl)
	initialization := NewInitialization(userRepositoryImpl, userServiceImpl, userControllerImpl)
	return initialization
}

// injector.go:

var db = wire.NewSet(ConnectToDB)

var userServiceSet = wire.NewSet(services.UserServiceInit, wire.Bind(new(services.IUserService), new(*services.UserServiceImpl)))

var userRepoSet = wire.NewSet(repositories.UserRepositoryInit, wire.Bind(new(repositories.IUserRepository), new(*repositories.UserRepositoryImpl)))

var userCtrlSet = wire.NewSet(controllers.UserControllerInit, wire.Bind(new(controllers.IUserController), new(*controllers.UserControllerImpl)))
